site_name: geotiff-to-wps
site_description: 

repo_url: https://github.com/geotiff-to-wps
repo_name: mullenkamp/geotiff-to-wps

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: light green
          accent: orange
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: light green
          accent: orange
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [.]
                import:
                    - https://docs.python.org/3.11/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - geotiff_to_wps

nav:
    - About: index.md
    - Reference:
        - geotiff_to_wps: reference/geotiff_to_wps.md
