"""Presets for common WPS static data types."""

PRESETS = {
    'dem': {
        'data_type': 'continuous',
        'signed': True,
        'wordsize': 2,
        'tile_bdr': 3,
        'missing_value': -9999,
        'scale_factor': None,
        'units': 'meters',
        'description': 'Topography height',
    },
    'landuse': {
        'data_type': 'categorical',
        'signed': False,
        'wordsize': 1,
        'tile_bdr': 0,
        'missing_value': 255,
        'scale_factor': None,
        'units': '',
        'description': 'Land use category',
        'category_min': 1,
    },
    'soiltype': {
        'data_type': 'categorical',
        'signed': False,
        'wordsize': 1,
        'tile_bdr': 0,
        'missing_value': 255,
        'scale_factor': None,
        'units': '',
        'description': 'Soil type category',
        'category_min': 1,
    },
    'greenfrac': {
        'data_type': 'continuous',
        'signed': True,
        'wordsize': 2,
        'tile_bdr': 3,
        'missing_value': -9999,
        'scale_factor': 0.001,
        'units': 'fraction',
        'description': 'Green vegetation fraction',
    },
    'albedo': {
        'data_type': 'continuous',
        'signed': True,
        'wordsize': 2,
        'tile_bdr': 3,
        'missing_value': -9999,
        'scale_factor': 0.001,
        'units': 'fraction',
        'description': 'Albedo',
    },
}
